server:
   port: 8003
   
# 定义当前服务名
spring:
   application:
      name: bsuser
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/bookshop?serverTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
      username: root
      password: a
      driver-class-name: com.mysql.jdbc.Driver

logging:
   level:
<<<<<<< HEAD
      com.yc.bookshop.dao: debug
      
mybatis:
   configuration:
      mapUnderscoreToCamelCase: true
=======
      com.yc.bookshop.dao: debug
>>>>>>> branch 'master' of https://github.com/sanqixiangmul/S3-bookshop.git
