server:
   port: 8003
   
# 定义当前服务名
spring:
   application:
      name: cruser
   datasource:
      url: jdbc:mysql://127.0.0.1:3307/bookshop?serverTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
      username: root
      password: a
      driver-class-name: com.mysql.jdbc.Driver

logging:
   level:
      com.yc.crbook.dao: debug